name: Release

on: workflow_dispatch

jobs:
  run_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run Script
        run: chmod u+x init.sh && ./init.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v0.0.2"
          name: Release ${{ github.ref }}
          draft: false
          files: ./release/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
